/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content;

import inc.koneksi;
import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Nama : Aceng Abdul Wahid
 * NIM  : A2.1700001
 * @author Ceng
 */
public class data_penjualan extends javax.swing.JPanel {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel,tabmodel1;
    
    Connection conn = inc.koneksi.Conn();
    
    /**
     * Creates new form data_penjualan
     */
    public data_penjualan() {
        initComponents();
        AutoKodePre();
        AutoKodeTrans();
        KodePel();
        tabelBuku();
        tampil_buku();
        tabelJual();
        tampil_jual();
        tblBuku.setModel(tabmodel);
        tblJual.setModel(tabmodel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdPreTransaksi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdPelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdBuku = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJual = new javax.swing.JTable();
        btnSelesai = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        totalHarga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        struk = new javax.swing.JTextArea();
        idTransaksi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stok_tampung = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Buku", "Judul", "Stok", "Harga"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cari.PNG"))); // NOI18N
        jLabel6.setToolTipText("Cari");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kode Pesan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kode Transaksi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kode Pelanggan");

        txtIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPelangganActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Kode Buku");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Judul");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Harga");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Jumlah");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Harga");

        txtIdBuku.setEnabled(false);
        txtIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBukuActionPerformed(evt);
            }
        });

        txtJudul.setEnabled(false);

        txtHargaJual.setEnabled(false);

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });

        txtTotal.setEnabled(false);

        btnTambah.setBackground(new java.awt.Color(204, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkout.png"))); // NOI18N
        btnTambah.setToolTipText("Order");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnTambahKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtIdPreTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPreTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Copyright 2019 | All Right Reserved | Aceng Abdul Wahid");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        tblJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pesan", "Kode Transaksi", "Kode Pelanggan", "Kode Buku", "Jumlah", "Sub Total"
            }
        ));
        tblJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJualMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJual);

        btnSelesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy shop.png"))); // NOI18N
        btnSelesai.setToolTipText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel shop.png"))); // NOI18N
        btnBatal.setToolTipText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total Harga");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Bayar");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Customer");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Kembalian");

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy.png"))); // NOI18N
        btnBayar.setToolTipText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finish.png"))); // NOI18N
        finish.setToolTipText("Cetak Struk");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        struk.setColumns(20);
        struk.setRows(5);
        jScrollPane3.setViewportView(struk);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kode Transaksi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnBayar)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel17)))
                                            .addComponent(jLabel15)
                                            .addComponent(totalHarga))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamaPelanggan)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPelanggan)
                            .addComponent(jLabel16)))
                    .addComponent(btnSelesai)
                    .addComponent(btnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(finish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(stok_tampung, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(stok_tampung, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void AutoKodePre(){
           try{
                rs = conn.createStatement().executeQuery("SELECT * FROM penjualan ORDER BY id_pretransaksi DESC");
                if(rs.next()){
                    String kode = rs.getString("id_pretransaksi").substring(3);
                    String AN = "" + (Integer.parseInt(kode) + 1);
                    String Nol = "";
             
                    if(AN.length() == 1){
                        Nol = "000";
                    }else if(AN.length() == 2){
                        Nol = "00";
                    }else if(AN.length() == 3){
                        Nol = "0";
                    }else if(AN.length() == 4){
                        Nol = "";
                    }
                    txtIdPreTransaksi.setText("PS" + Nol + AN);
                } else{
                    txtIdPreTransaksi.setText("PS0001");
                }
                txtIdPreTransaksi.enable(false);
                rs.close();
           }catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            } 
        }
    
    public void AutoKodeTrans(){
           try{
                rs = conn.createStatement().executeQuery("SELECT * FROM penjualan2 ORDER BY id_transaksi DESC");
                if(rs.next()){
                    String kode = rs.getString("id_transaksi").substring(3);
                     String AN = "" + (Integer.parseInt(kode) + 1);
                     String Nol = "";
                    
                    if(AN.length() == 1){
                      Nol = "000";
                    }else if(AN.length() == 2){
                        Nol = "00";
                    }else if(AN.length() == 3){
                         Nol = "0";
                    }else if(AN.length() == 4){
                        Nol = "";
                    }
                    txtIdTransaksi.setText("TR" + Nol + AN);
             
                } else{
                    txtIdTransaksi.setText("TR0001");
                }
                txtIdTransaksi.enable(false);
                rs.close();
           }catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    
    public void KodePel(){
        txtIdPelanggan.requestFocus();   
            try{
                rs = conn.createStatement().executeQuery("SELECT * FROM pelanggan");
                if(rs.next()){
                    String kode = rs.getString("id_pelanggan").substring(3);
                     String AN = "" + (Integer.parseInt(kode) + 1);
                     String Nol = "";
                    
                    if(AN.length() == 1){
                      Nol = "000";
                    }else if(AN.length() == 2){
                        Nol = "00";
                    }else if(AN.length() == 3){
                         Nol = "0";
                    }else if(AN.length() == 4){
                        Nol = "";
                    }
                    txtIdPelanggan.setText("PL" + Nol + AN);
             
                } else{
                    txtIdPelanggan.setText("PL0001");
                }
                txtIdPelanggan.enable(true);
                rs.close();
           }catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    
    public void tabelBuku(){
        Object[] judul = {"Id Buku","Judul","Stok","Harga"};
        tabmodel = new DefaultTableModel(null,judul){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblBuku.setModel(tabmodel);
    }
    
     public void tabelJual(){
        Object[] judul = {"Kode Pesan","Kode Transaksi","Kode Pelanggan","Kode Buku","Jumlah","Sub Total"};
        tabmodel1 = new DefaultTableModel(null,judul){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblJual.setModel(tabmodel1);
    }
    
    public void tampil_jual(){
        try {
            st = conn.createStatement();
            tabmodel1.getDataVector().removeAllElements();
            tabmodel1.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM penjualan");
            while (rs.next()) {                
                Object[] data = {
                    rs.getString("id_pretransaksi"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_pelanggan"),
                    rs.getString("id_buku"),
                    rs.getString("jumlah"),
                    rs.getString("sub_total"),
                };
                tabmodel1.addRow(data);
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void tampil_buku(){
        try {
            st = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT id_buku,judul,stok,harga_jual FROM buku");
            while (rs.next()) {                
                Object[] data = {
                    rs.getString("id_buku"),
                    rs.getString("judul"),
                    rs.getString("stok"),
                    rs.getString("harga_jual"),
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void reset(){
        txtIdBuku.setText("");
        txtJudul.setText("");
        txtJumlah.setText("");
        txtHargaJual.setText("");
        txtTotal.setText("");
    }
    
    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        try{
            st = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM buku WHERE id_buku like '%" + txtCari.getText() + "%' or judul like '%" + txtCari.getText() + "%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_buku"),
                    rs.getString("judul"),
                    rs.getString("stok"),
                    rs.getString("harga_jual"),
                };
                tabmodel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
        if (txtIdPelanggan.getText().equals("") || txtIdBuku.getText().equals("") || txtHargaJual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data");
        }
        else{
            if (txtJumlah.getText().toString().equals("")) {
                txtJumlah.setText("");
                txtTotal.setText("");
            }
            else{
                int stok = Integer.parseInt(String.valueOf(stok_tampung.getText()));
                int a    = Integer.parseInt(String.valueOf(txtJumlah.getText()));
                int b    = Integer.parseInt(String.valueOf(txtHargaJual.getText()));
                
                if (a > stok) {
                    JOptionPane.showMessageDialog(null, "Stok Hanya Tersedia " + stok);
                }
                else{
                    int jumlah = a * b;
                    txtTotal.setText(String.valueOf(jumlah));
                }
            }
        }
    }//GEN-LAST:event_txtJumlahKeyReleased

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }

        if (txtIdPelanggan.getText().equals("") || txtIdBuku.getText().equals("") || txtHargaJual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data");
        }
        else{
            if (txtJumlah.getText().toString().equals("")) {
                txtJumlah.setText("");
                txtTotal.setText("");
            }
            else{
                int stok = Integer.parseInt(String.valueOf(stok_tampung.getText()));
                int a    = Integer.parseInt(String.valueOf(txtJumlah.getText()));
                int b    = Integer.parseInt(String.valueOf(txtHargaJual.getText()));
                
                if (a > stok) {
                    JOptionPane.showMessageDialog(null, "Stok Hanya Tersedia " + stok);
                }
                else{
                    int jumlah = a * b;
                    txtTotal.setText(String.valueOf(jumlah));
                }
            }
        }
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (txtIdPelanggan.getText().equals("") || txtIdBuku.getText().equals("") || txtHargaJual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data...");
        }
        try {
            st = conn.createStatement();
            st.executeUpdate("INSERT INTO penjualan SET " + " id_pretransaksi='"+ txtIdPreTransaksi.getText() +"', id_transaksi='"+ txtIdTransaksi.getText() +"', id_pelanggan='"+ txtIdPelanggan.getText() +"', id_buku='"+ txtIdBuku.getText() +"', jumlah='"+ txtJumlah.getText() +"', sub_total='"+ txtTotal.getText() +"'");
            JOptionPane.showMessageDialog(null, "Berhasil Di Tambah Ke Keranjang");
            AutoKodePre();
            KodePel();
            tampil_buku();
            tabelJual();
            tampil_jual();
            reset();
            btnBatal.setEnabled(true);
            btnSelesai.setEnabled(true);
            finish.setEnabled(true);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahKeyReleased

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT SUM(sub_total) FROM penjualan WHERE " + " id_transaksi='"+ txtIdTransaksi.getText() +"'");
            while(rs.next()){
                totalHarga.setText(rs.getString(1));
                idTransaksi.setText(txtIdTransaksi.getText());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       int pilih = JOptionPane.showConfirmDialog(null,"Batal Beli ?","Confirmation",JOptionPane.YES_NO_OPTION);
       if(pilih == JOptionPane.NO_OPTION){
           
       }
       else
       {
           try {
               st = conn.createStatement();
               st.executeUpdate("DELETE FROM penjualan WHERE" + " id_pretransaksi='"+ label1.getText() +"'");
               tampil_jual();
               tampil_buku();
               AutoKodePre();
               totalHarga.setText("");
               txtBayar.setText("");
               txtKembalian.setText("");
               label1.setText("");
           } catch (Exception e) {
               System.out.println(e.getMessage());
           }
       }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        if (totalHarga.getText().equals("") || txtBayar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Data Dahulu");
        }
        else
        {
            int total = Integer.parseInt(String.valueOf(totalHarga.getText()));
            int bayarr = Integer.parseInt(String.valueOf(txtBayar.getText()));
            if (total > bayarr) {
                JOptionPane.showMessageDialog(null, "Maaf uang anda kurang");
            }
            else
            {
                int hasil = bayarr - total;
                txtKembalian.setText(String.valueOf(hasil));
                try {
                    st = conn.createStatement();
                    st.executeUpdate("INSERT INTO penjualan2 SET" + " id_transaksi='"+ txtIdTransaksi.getText() +"', nama_pelanggan='"+ txtNamaPelanggan.getText() +"', total='"+ totalHarga.getText() +"'");
//                    
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
        
        try{
                st = conn.createStatement();
                rs = st.executeQuery("select * from struk_bayar where "+ "id_transaksi='" + idTransaksi.getText() + "'");
                if (rs.next()) {
                    struk.setText("                                   Ceng_BookStore                      "+
                        "\n     Jl. Siliwangi No 65 Kab.Majalengka,Jawa Barat,Indonesia"+
                        "\n                           Telp(082118771688)"+
                        "\n--------------------------------------------------------------------------------"+
                        "\nNomor Transaksi\t= " + rs.getString("id_transaksi") +
                        "\nNama Pelanggan\t= " + rs.getString("nama_pelanggan") +
                        "\nJudul Buku\t\t= " + rs.getString("judul") +
                        "\nWaktu \t\t= " + rs.getString("tanggal_beli") +                        
                        "\n--------------------------------------------------------------------------------"+
                        "\nHarga Buku\t\t= " + "Rp."+ rs.getString("harga_jual") +
                        "\nJumlah Buku\t\t= " + rs.getString("jumlah") +
                        "\nTotal Harga\t\t= " + "Rp."+rs.getString("total") +
                        "\n--------------------------------------------------------------------------------"+
                        "\nBayar\t\t= " + "Rp."+txtBayar.getText() +
                        "\nKembalian\t\t= " + "Rp."+txtKembalian.getText() +

                        "\n--------------------------------------------------------------------------------"+
                        "\n Terima Kasih Telah Membeli Buku di Ceng_Bookstore"+
                        "\n Semoga Menambah Wawasan dan Ilmu yang bermanfaat "+
                        "\n -----------------------***---------------------- "
                    );
                }else{
                    JOptionPane.showMessageDialog(null, "Nomor transaksi tidak ditemukan!");
                    txtIdTransaksi.requestFocus();
                    txtIdTransaksi.setText("");
                    struk.setText("");
                }
            }catch(Exception e){
                e.printStackTrace();
            }

        
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        txtIdBuku.setText(tabmodel.getValueAt(tblBuku.getSelectedRow(), 0).toString());
        stok_tampung.setText(tabmodel.getValueAt(tblBuku.getSelectedRow(), 2).toString());
        txtJudul.setText(tabmodel.getValueAt(tblBuku.getSelectedRow(),1).toString());
        txtHargaJual.setText(tabmodel.getValueAt(tblBuku.getSelectedRow(), 3).toString());
//        btnTambah.setEnabled(false);
    }//GEN-LAST:event_tblBukuMouseClicked

    private void tblJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJualMouseClicked
//        label1.setText(tabmodel1.getValueAt(tblJual.getSelectedRow(), 0).toString());
//        idTransaksi.setText(tabmodel1.getValueAt(tblJual.getSelectedRow(), 1).toString());
//        txtIdPelanggan.setText(tabmodel1.getValueAt(tblJual.getSelectedRow(), 2).toString());
//        totalHarga.setText(tabmodel1.getValueAt(tblJual.getSelectedRow(), 5).toString());
//
//        btnSelesai.setEnabled(true);
//        btnBatal.setEnabled(true);
//        finish.setEnabled(true);
//        label1.getText();
    }//GEN-LAST:event_tblJualMouseClicked

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
            try{
                new data_penjualan().printComponents(null);
                struk.print();
                idTransaksi.setText("");
                struk.setText("");
                JOptionPane.showMessageDialog(null,"Transaksi Selesai");
                    AutoKodeTrans();
                    KodePel();
                    tampil_jual();
                    totalHarga.setText("");
                    txtNamaPelanggan.setText("");
                    txtBayar.setText("");
                    txtKembalian.setText("");
            }catch(Exception e){
            System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_finishActionPerformed

    private void txtIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPelangganActionPerformed
        txtIdPelanggan.requestFocus();
        try {
            String sql = "Select * from pelanggan where id_pelanggan='"+txtIdPelanggan.getText()+"'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                txtNamaPelanggan.setText(rs.getString("nama_pelanggan"));
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtIdPelangganActionPerformed

    private void txtIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBukuActionPerformed
        txtIdBuku.requestFocus();
        try {
            String sql = "Select * from buku where id_buku='"+txtIdBuku.getText()+"'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                txtJudul.setText(rs.getString("judul"));
                int harga    = rs.getInt("harga_jual");
                txtHargaJual.setText(String.valueOf(harga));

            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtIdBukuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton finish;
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel stok_tampung;
    private javax.swing.JTextArea struk;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTable tblJual;
    private javax.swing.JTextField totalHarga;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtIdPreTransaksi;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
